Footer
Nefalit/nft-market-place pull request #2
Opened 2022-06-23 06:44 UTC by RomanFrontman

2022-06-23 12:43 UTC, yuriikohut requested changes

2022-06-23 12:43 UTC, yuriikohut commented on my-app/src/components/Footer/footer.css
> +    background-color: #485470;
було б класно винести кольори в константи

А ви не думали scss використовувати?

2022-06-23 12:43 UTC, yuriikohut commented on my-app/src/components/Footer/footer.css
> +.wrapper {
тут просто сss файл (не module.css), через то можуть бути проблеми в подальшому, якщо ти будеш використовувати в інших компонентах такі назви класів. Нагадати собі за модулі можна тут - https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/

2022-06-23 12:43 UTC, yuriikohut commented on my-app/src/components/Footer/footer.jsx
> +                        <img src={logo} alt=""/>
alt пустий

2022-06-23 14:14 UTC, RomanFrontman commented on my-app/src/components/Footer/footer.css
> +    background-color: #485470;
домовились юзати css, та як не дуже великий проект

2022-06-24 08:54 UTC, yuriikohut approved these changes

2022-06-24 09:07 UTC, merged